# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: cd admin-panel && yarn # runs during prebuild
    command: cd admin-panel && yarn start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3006
    onOpen: open-preview
