/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:3886947d-f7df-404f-8cb8-0eaab4c778f7",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_BKpV92Nvj",
    "aws_user_pools_web_client_id": "675k8mppu1ovdl5b7nq2b4l4ul",
    "oauth": {},
    "aws_user_files_s3_bucket": "queensmanclient12080606a9af447f87f3fad2d5d3006b13442-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
