# hasura configuration for the CLI
version: 2
metadata_directory: metadata

# hasura configuration for the project
hasura_graphql_version: v2.0.0-alpha.6
hasura_graphql_port: 8080
hasura_graphql_admin_secret: 123456

# hasura backend plus configuration
hasura_backend_plus_version: v2.2.4
hasura_backend_plus_port: 9001

# postgres configuration
postgres_version: 12.0
postgres_port: 5432
postgres_user: postgres
postgres_password: postgres

# minio
minio_port: 9000

# api
api_port: 4000

# custom environment variables for Hasura GraphQL engine: webhooks, headers, etc
env_file: ../.env.development

# OAuth services
provider_success_redirect: http://localhost:3000
provider_failure_redirect: http://localhost:3000/login-fail

google_enable: false
google_client_id:
google_client_secret:

github_enable: false
github_client_id:
github_client_secret:

facebook_enable: false
facebook_client_id:
facebook_client_secret:

linkedin_enable: false
linkedin_client_id:
linkedin_client_secret:
